function BasicParams()
%% Initialize the basic parmeters

    global remoteHPC zipDataFiles availableNodes ProcSchemes defaultGeometry
    
    % Whether to conduct simulation on remote HPC cluster
    remoteHPC = true;
    
    % Whether to ZIP I/O data files before transferring through network
    zipDataFiles = false;
    
    defaultGeometry = 'default - AstroGeometry'; 
    
    % Names of all cluster nodes you may want to use in the simulation
    % (must be kept in sync with those ones defined in "hpc\hostfile_BusyMaster and hpc\hostfile_IdleMaster")
    availableNodes = {'tuxmaster', ...
                      'tuxm1', ...
                      'tuxm2', ...
                      'tuxm3', ...
                      'tuxm4', ...
                      'tuxm5', ...
                      'tuxm6', ...
                      'tuxm7', ...
                      'tuxm8', ...
                      'tuxm9', ...
                      'tuxm10', ...
                      'tuxm11', ...
                      'tuxm12'};
    
    % The process distribution scheme
    ProcSchemes = struct('OnlyMaster', 1, ...
                         'OnlySlaves', 2, ...
                         'MasterAndSlaves', 3);

end
