#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/savtchenko/amcbridge/phase14/nano/clusterCaSim/hpc/x86_64/.libs/libnrnmech.so" "$@"
